name: Build and test etc3 controller

on:
  # Run tests for any PRs.
  pull_request:

env:
  IMG: controller

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Run Kubernetes tools
      uses: stefanprodan/kube-tools@v1
      with:
        kubectl: 1.18.2
        kustomize: 3.5.5
    - name: Set up Kubebuilder 2.3.1
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)

        # download kubebuilder and extract it to tmp
        curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/

        # move to a long-term location and put it on your path
        # (you'll need to set the KUBEBUILDER_ASSETS env var if you put it somewhere else)
        sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: make test